spring:
  #数据源 mysql
  datasource:
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: ronger611
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.imust.layui.mapper : DEBUG